let data = [
  {
    address: "7598 Duneiden Lane",
    image: "images/img-1.jpg",
    ImgAgent: "images/img-1.jpg",
    agent: "Gabriel Fono",
    post: "june 20 1991",
    price: "4000000",
    city: "manassas",
    bed: "7bed rooms",
    extras: ["Elevator", "SwimmingPool", "Finished basement", "gyms"],
  },
  {
    address: "8383 Fairfax County",
    image: "images/img-2.jpg",
    ImgAgent: "images/img-2.jpg",
    agent: "Tabongue Yannick",
    post: "November 19,1990",
    price: "3000000",
    city: "Fairfax",
    bed: "3bed rooms",
    extras: ["Elevator", "SwimmingPool", "Finished basement", "gyms"],
  },
  {
    address: "78983 Woodbridge ",
    image: "images/img-3.jpg",
    ImgAgent: "images/img-3.jpg",
    agent: "Gabriel batisseur",
    post: "October 19,1930",
    price: "5000000",
    city: "Woodbrige",
    bed: "9bed rooms",
    extras: ["Elevator", "SwimmingPool", "Finished basement", "gyms"],
  },
];
export default data;
